//
//  KeyCodes.swift
//
//  Created by Zakk Hoyt on 12/23/17.
//  Copyright © 2017 Zakk Hoyt. All rights reserved.
//
//
//  These key code constants are wrappers around Carbon's
//  <HIToolbox/Events.h> header file. This just provides
//  swifty syntax sugar. Think of it as "NSKeyCode".

import Carbon

struct KeyCode {
    static let keyA = UInt16(kVK_ANSI_A)
    static let keyB = UInt16(kVK_ANSI_B)
    static let keyC = UInt16(kVK_ANSI_C)
    static let keyD = UInt16(kVK_ANSI_D)
    static let keyE = UInt16(kVK_ANSI_E)
    static let keyF = UInt16(kVK_ANSI_F)
    static let keyG = UInt16(kVK_ANSI_G)
    static let keyH = UInt16(kVK_ANSI_H)
    static let keyI = UInt16(kVK_ANSI_I)
    static let keyJ = UInt16(kVK_ANSI_J)
    static let keyK = UInt16(kVK_ANSI_K)
    static let keyL = UInt16(kVK_ANSI_L)
    static let keyM = UInt16(kVK_ANSI_M)
    static let keyN = UInt16(kVK_ANSI_N)
    static let keyO = UInt16(kVK_ANSI_O)
    static let keyP = UInt16(kVK_ANSI_P)
    static let keyQ = UInt16(kVK_ANSI_Q)
    static let keyR = UInt16(kVK_ANSI_R)
    static let keyS = UInt16(kVK_ANSI_S)
    static let keyT = UInt16(kVK_ANSI_T)
    static let keyU = UInt16(kVK_ANSI_U)
    static let keyV = UInt16(kVK_ANSI_V)
    static let keyW = UInt16(kVK_ANSI_W)
    static let keyX = UInt16(kVK_ANSI_X)
    static let keyY = UInt16(kVK_ANSI_Y)
    static let keyZ = UInt16(kVK_ANSI_Z)
    
    static let key0 = UInt16(kVK_ANSI_0)
    static let key1 = UInt16(kVK_ANSI_1)
    static let key2 = UInt16(kVK_ANSI_2)
    static let key3 = UInt16(kVK_ANSI_3)
    static let key4 = UInt16(kVK_ANSI_4)
    static let key5 = UInt16(kVK_ANSI_5)
    static let key6 = UInt16(kVK_ANSI_6)
    static let key7 = UInt16(kVK_ANSI_7)
    static let key8 = UInt16(kVK_ANSI_8)
    static let key9 = UInt16(kVK_ANSI_9)
    
    static let keyKeypad0 = UInt16(kVK_ANSI_Keypad0)
    static let keyKeypad1 = UInt16(kVK_ANSI_Keypad1)
    static let keyKeypad2 = UInt16(kVK_ANSI_Keypad2)
    static let keyKeypad3 = UInt16(kVK_ANSI_Keypad3)
    static let keyKeypad4 = UInt16(kVK_ANSI_Keypad4)
    static let keyKeypad5 = UInt16(kVK_ANSI_Keypad5)
    static let keyKeypad6 = UInt16(kVK_ANSI_Keypad6)
    static let keyKeypad7 = UInt16(kVK_ANSI_Keypad7)
    static let keyKeypad8 = UInt16(kVK_ANSI_Keypad8)
    static let keyKeypad9 = UInt16(kVK_ANSI_Keypad9)
    static let keyKeypadClear = UInt16(kVK_ANSI_KeypadClear)
    static let keyKeypadDivide = UInt16(kVK_ANSI_KeypadDivide)
    static let keyKeypadEnter = UInt16(kVK_ANSI_KeypadEnter)
    static let keyKeypadEquals = UInt16(kVK_ANSI_KeypadEquals)
    static let keyKeypadMinus = UInt16(kVK_ANSI_KeypadMinus)
    static let keyKeypadPlus = UInt16(kVK_ANSI_KeypadPlus)
    static let keyPageDown = UInt16(kVK_PageDown)
    static let keyPageUp = UInt16(kVK_PageUp)
    static let keyEnd = UInt16(kVK_End)
    static let keyHome = UInt16(kVK_Home)

    static let keyF1 = UInt16(kVK_F1)
    static let keyF2 = UInt16(kVK_F2)
    static let keyF3 = UInt16(kVK_F3)
    static let keyF4 = UInt16(kVK_F4)
    static let keyF5 = UInt16(kVK_F5)
    static let keyF6 = UInt16(kVK_F6)
    static let keyF7 = UInt16(kVK_F7)
    static let keyF8 = UInt16(kVK_F8)
    static let keyF9 = UInt16(kVK_F9)
    static let keyF10 = UInt16(kVK_F10)
    static let keyF11 = UInt16(kVK_F11)
    static let keyF12 = UInt16(kVK_F12)
    static let keyF13 = UInt16(kVK_F13)
    static let keyF14 = UInt16(kVK_F14)
    static let keyF15 = UInt16(kVK_F15)
    static let keyF16 = UInt16(kVK_F16)
    static let keyF17 = UInt16(kVK_F17)
    static let keyF18 = UInt16(kVK_F18)
    static let keyF19 = UInt16(kVK_F19)
    static let keyF20 = UInt16(kVK_F20)

    static let keyApostrophe = UInt16(kVK_ANSI_Quote)
    static let keyBackApostrophe = UInt16(kVK_ANSI_Grave)
    static let keyBackslash = UInt16(kVK_ANSI_Backslash)
    static let keyCapsLock = UInt16(kVK_CapsLock)
    static let keyComma = UInt16(kVK_ANSI_Comma)
    static let keyHelp = UInt16(kVK_Help)
    static let keyForwardDelete = UInt16(kVK_ForwardDelete)
    static let keyDecimal = UInt16(kVK_ANSI_KeypadDecimal)
    static let keyDelete = UInt16(kVK_Delete)
    static let keyEquals = UInt16(kVK_ANSI_Equal)
    static let keyEscape = UInt16(kVK_Escape)
    static let keyLeftBracket = UInt16(kVK_ANSI_LeftBracket)
    static let keyMinus = UInt16(kVK_ANSI_Minus)
    static let keyMultiply = UInt16(kVK_ANSI_KeypadMultiply)
    static let keyPeriod = UInt16(kVK_ANSI_Period)
    static let keyReturn = UInt16(kVK_Return)
    static let keyRightBracket = UInt16(kVK_ANSI_RightBracket)
    static let keySemicolon = UInt16(kVK_ANSI_Semicolon)
    static let keySlash = UInt16(kVK_ANSI_Slash)
    static let keySpace = UInt16(kVK_Space)
    static let keyTab = UInt16(kVK_Tab)

    static let keyMute = UInt16(kVK_Mute)
    static let keyVolumeDown = UInt16(kVK_VolumeDown)
    static let keyVolumeUp = UInt16(kVK_VolumeUp)

    static let keyCommand = UInt16(kVK_Command)
    static let keyRightCommand = UInt16(kVK_RightCommand)
    static let keyControl = UInt16(kVK_Control)
    static let keyRightControl = UInt16(kVK_RightControl)
    static let keyFunction = UInt16(kVK_Function)
    static let keyOption = UInt16(kVK_Option)
    static let keyRightOption = UInt16(kVK_RightOption)
    static let keyShift = UInt16(kVK_Shift)
    static let keyRightShift = UInt16(kVK_RightShift)
    
    static let keyDownArrow = UInt16(kVK_DownArrow)
    static let keyLeftArrow = UInt16(kVK_LeftArrow)
    static let keyRightArrow = UInt16(kVK_RightArrow)
    static let keyUpArrow = UInt16(kVK_UpArrow)
}
